import type { Metadata } from "next";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { TableOfContents } from "@/components/legal/TableOfContents";
import { LegalSection } from "@/components/legal/LegalSection";
import Navbar from "@/components/landing/Navbar";
import LandingFooter from "@/components/landing/LandingFooter";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for Postify - How we collect, use, and protect your data",
};

const sections = [
  { id: "collection", title: "Information We Collect" },
  { id: "usage", title: "How We Use Your Information" },
  { id: "ai-processing", title: "AI Processing of Your Data" },
  { id: "storage", title: "Data Storage & Security" },
  { id: "third-party", title: "Third-Party Services" },
  { id: "retention", title: "Data Retention" },
  { id: "rights", title: "Your Rights" },
  { id: "cookies", title: "Cookies & Analytics" },
  { id: "children", title: "Children's Privacy" },
  { id: "changes", title: "Changes to this Policy" },
  { id: "contact", title: "Contact Us" },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#F9F7F4]">
      <Navbar />
      
      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
        <div className="lg:grid lg:grid-cols-[1fr_250px] lg:gap-12">
          <div className="max-w-3xl">
            <div className="mb-8">
              <Badge className="mb-4 bg-[#7C9EE8]/10 text-[#7C9EE8] border-[#7C9EE8]/20">
                Last updated: January 15, 2025
              </Badge>
              <h1 className="text-4xl sm:text-5xl font-bold text-[#1C1917] mb-4 font-[family-name:var(--font-display)]">
                Privacy Policy
              </h1>
              <p className="text-lg text-[#78716C]">
                Your privacy is important to us. This policy explains how we collect, use, and protect your data.
              </p>
            </div>

            <div className="space-y-12">
              <LegalSection id="collection" title="Information We Collect">
                <p>
                  Postify collects the following types of information to provide and improve our Service:
                </p>
                
                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">1. Google OAuth Information</h3>
                  <p>When you sign up using Google OAuth, we collect:</p>
                  <ul className="list-disc pl-6 space-y-1 mt-2">
                    <li><strong>Email address:</strong> For account identification and communication</li>
                    <li><strong>Full name:</strong> For personalization within the platform</li>
                    <li><strong>Profile picture (avatar):</strong> Displayed in your dashboard</li>
                  </ul>
                </div>

                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">2. CV and Resume Content</h3>
                  <p>
                    When you upload your CV, we store the file and extract text content for AI processing. 
                    This may include your work history, education, skills, and contact information.
                  </p>
                </div>

                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">3. Job Description Data</h3>
                  <p>
                    Job descriptions you input are temporarily processed to generate tailored cover letters. 
                    We may retain this data to improve our AI models.
                  </p>
                </div>

                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">4. Generated Content</h3>
                  <p>
                    Cover letters generated by our AI, along with application history (recipient emails, subjects, dates).
                  </p>
                </div>

                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">5. Usage Data</h3>
                  <p>
                    We automatically collect technical information including IP address, browser type, device information, 
                    and usage patterns to improve the Service.
                  </p>
                </div>
              </LegalSection>

              <LegalSection id="usage" title="How We Use Your Information">
                <p>We use your information for the following purposes:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Service Delivery:</strong> To provide AI-generated cover letters and email sending functionality</li>
                  <li><strong>Account Management:</strong> To create and maintain your account, authenticate access</li>
                  <li><strong>Personalization:</strong> To tailor cover letters based on your CV and job descriptions</li>
                  <li><strong>Communication:</strong> To send service updates, security alerts, and support messages</li>
                  <li><strong>Improvement:</strong> To analyze usage patterns and improve AI model accuracy</li>
                  <li><strong>Security:</strong> To detect and prevent fraud, abuse, and security incidents</li>
                  <li><strong>Legal Compliance:</strong> To comply with legal obligations and enforce our Terms</li>
                </ul>
                <p className="mt-4">
                  <strong>We do not sell your personal information to third parties.</strong>
                </p>
              </LegalSection>

              <LegalSection id="ai-processing" title="AI Processing of Your Data">
                <p>
                  Postify uses artificial intelligence to analyze your CV and job descriptions to generate personalized 
                  cover letters. Here&apos;s how your data is processed:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Your CV content is parsed and analyzed to extract relevant skills, experience, and qualifications</li>
                  <li>Job descriptions are analyzed to identify key requirements and company information</li>
                  <li>Our AI models combine this information to generate tailored cover letters</li>
                  <li>AI processing may involve third-party AI service providers (see Third-Party Services section)</li>
                  <li>Your data may be used to improve AI model performance, but is anonymized when possible</li>
                </ul>
                <p className="mt-4">
                  You retain full ownership of your CV and personal information. AI-generated content is provided to you 
                  for your use and review before sending.
                </p>
              </LegalSection>

              <LegalSection id="storage" title="Data Storage & Security">
                <p>
                  We take data security seriously and implement industry-standard measures to protect your information:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Encryption:</strong> Data is encrypted in transit (HTTPS/TLS) and at rest</li>
                  <li><strong>Access Controls:</strong> Strict access controls limit who can view your data</li>
                  <li><strong>Secure Storage:</strong> Files are stored on secure cloud infrastructure with regular backups</li>
                  <li><strong>Authentication:</strong> OAuth 2.0 for secure account access without storing passwords</li>
                  <li><strong>Monitoring:</strong> Continuous monitoring for security threats and vulnerabilities</li>
                </ul>
                <p className="mt-4">
                  However, no method of transmission or storage is 100% secure. While we strive to protect your data, 
                  we cannot guarantee absolute security.
                </p>
              </LegalSection>

              <LegalSection id="third-party" title="Third-Party Services">
                <p>
                  Postify integrates with the following third-party services to provide functionality:
                </p>
                
                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">Google OAuth & Gmail</h3>
                  <p>
                    We use Google OAuth for authentication and Gmail API for sending emails on your behalf. 
                    Google&apos;s privacy practices are governed by their{" "}
                    <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" 
                       className="text-[#7C9EE8] hover:underline">
                      Privacy Policy
                    </a>.
                  </p>
                </div>

                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">AI Service Providers</h3>
                  <p>
                    We may use third-party AI services (such as OpenAI) to process your CV and generate cover letters. 
                    These providers have their own privacy policies and data handling practices.
                  </p>
                </div>

                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">Cloud Infrastructure</h3>
                  <p>
                    Your data is stored on secure cloud infrastructure providers. We select providers with strong 
                    security and privacy commitments.
                  </p>
                </div>

                <p className="mt-4">
                  We carefully vet all third-party services and require them to maintain appropriate security measures.
                </p>
              </LegalSection>

              <LegalSection id="retention" title="Data Retention">
                <p>
                  We retain your information for as long as necessary to provide the Service and comply with legal obligations:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Account Data:</strong> Retained while your account is active</li>
                  <li><strong>CVs:</strong> Stored until you delete them or close your account</li>
                  <li><strong>Application History:</strong> Retained for your reference until account deletion</li>
                  <li><strong>Usage Logs:</strong> Typically retained for 90 days for security and analytics</li>
                </ul>
                <p className="mt-4">
                  When you delete your account, we will delete or anonymize your personal information within 30 days, 
                  except where retention is required by law.
                </p>
              </LegalSection>

              <LegalSection id="rights" title="Your Rights">
                <p>
                  Depending on your location, you may have the following rights regarding your personal data:
                </p>
                
                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">GDPR Rights (EU/EEA Users)</h3>
                  <ul className="list-disc pl-6 space-y-1">
                    <li><strong>Access:</strong> Request a copy of your personal data</li>
                    <li><strong>Rectification:</strong> Correct inaccurate or incomplete data</li>
                    <li><strong>Erasure:</strong> Request deletion of your data (&quot;right to be forgotten&quot;)</li>
                    <li><strong>Portability:</strong> Receive your data in a machine-readable format</li>
                    <li><strong>Restriction:</strong> Limit how we process your data</li>
                    <li><strong>Objection:</strong> Object to certain types of processing</li>
                    <li><strong>Withdraw Consent:</strong> Withdraw consent for data processing</li>
                  </ul>
                </div>

                <div className="mt-4">
                  <h3 className="text-lg font-semibold text-[#1C1917] mb-2">CCPA Rights (California Users)</h3>
                  <ul className="list-disc pl-6 space-y-1">
                    <li><strong>Know:</strong> Request disclosure of data collection and sharing practices</li>
                    <li><strong>Delete:</strong> Request deletion of your personal information</li>
                    <li><strong>Opt-Out:</strong> Opt out of the sale of personal information (we do not sell data)</li>
                    <li><strong>Non-Discrimination:</strong> Equal service regardless of privacy choices</li>
                  </ul>
                </div>

                <p className="mt-4">
                  To exercise these rights, contact us at <strong>privacy@postify.app</strong>. 
                  We will respond within 30 days.
                </p>
              </LegalSection>

              <LegalSection id="cookies" title="Cookies & Analytics">
                <p>
                  Postify uses cookies and similar technologies to enhance your experience:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Essential Cookies:</strong> Required for authentication and core functionality</li>
                  <li><strong>Analytics Cookies:</strong> Help us understand how users interact with the Service</li>
                  <li><strong>Preference Cookies:</strong> Remember your settings and preferences</li>
                </ul>
                <p className="mt-4">
                  You can control cookies through your browser settings. Note that disabling cookies may affect 
                  Service functionality.
                </p>
              </LegalSection>

              <LegalSection id="children" title="Children's Privacy">
                <p>
                  Postify is not intended for users under the age of 16. We do not knowingly collect personal information 
                  from children under 16.
                </p>
                <p>
                  If we become aware that we have collected personal information from a child under 16, we will take 
                  steps to delete that information promptly.
                </p>
                <p>
                  If you believe a child under 16 has provided us with personal information, please contact us at 
                  <strong> privacy@postify.app</strong>.
                </p>
              </LegalSection>

              <LegalSection id="changes" title="Changes to this Policy">
                <p>
                  We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements.
                </p>
                <p>
                  When we make material changes, we will notify you via email or through a prominent notice in the Service. 
                  The &quot;Last updated&quot; date at the top of this policy indicates when it was last revised.
                </p>
                <p>
                  Your continued use of Postify after changes are posted constitutes acceptance of the updated policy.
                </p>
              </LegalSection>

              <LegalSection id="contact" title="Contact Us">
                <p>
                  If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, 
                  please contact us:
                </p>
                <div className="mt-4 space-y-2">
                  <p><strong>Email:</strong> privacy@postify.app</p>
                  <p><strong>Data Protection Officer:</strong> dpo@postify.app</p>
                </div>
                <p className="mt-4">
                  For general inquiries, see our{" "}
                  <Link href="/terms" className="text-[#7C9EE8] hover:underline font-semibold">
                    Terms & Conditions
                  </Link>.
                </p>
              </LegalSection>
            </div>

            <div className="mt-12 p-6 bg-white rounded-2xl border border-[#EAE7E3]">
              <p className="text-sm text-[#78716C]">
                By using Postify, you acknowledge that you have read and understood this Privacy Policy and our{" "}
                <Link href="/terms" className="text-[#7C9EE8] hover:underline font-semibold">
                  Terms & Conditions
                </Link>.
              </p>
            </div>
          </div>

          <aside className="hidden lg:block">
            <div className="sticky top-24">
              <TableOfContents items={sections} />
            </div>
          </aside>
        </div>
      </main>

      <LandingFooter />
    </div>
  );
}
